PROCEDURE STORE_SUPP is
enddate date;
startdate date;
BEGIN
DELETE STORE_STK_RIMS;
COMMIT;
startdate:=:startdate;
enddate:=:enddate;
IF :startdate IS NULL OR :enddate IS NULL THEN
dbms_output.put_line('Please eneter start and end date!');

ELSE
	--INSERTS STORE DATA TO STORE_STK_RIMS
	--FOOTWEAR
	INSERT INTO STORE_STK_RIMS (RM_NO,TRANS_NO,STORE_NO,ITEM_NO,WIDTH,TSTOCK,S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13)
	SELECT 'RM63',I.TRANS_NO,R.STORE_NO,SUBSTR(I.ITEM_NO,1,7)ITEM,I.WIDTH,SUM(NVL(I.RELEASED_QTY,0))TOTAL_PAIRS,
	NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
	--FROM WHS_TRANS_HDR H, WHS_TRANS_ITEM I, STORE R, TRANSFER_DAY D
	FROM WHS_TRANS_HDR H, WHS_TRANS_ITEM I, STORE R
	WHERE H.TRANS_NO=I.TRANS_NO
	--and   H.TRANS_NO=D.TRANS_NO
	--AND   D.TRANS_NO=I.TRANS_NO
	AND   H.SHIP_DATE BETWEEN :startdate and :enddate
	AND   H.FROM_DATE BETWEEN :startdate and :enddate
	--AND   D.DISPATCH_DATE BETWEEN :startdate and :enddate
    -- AND  H.FROM_DATE = TRUNC(SYSDATE)-1
     --AND   H.FROM_DATE =  TO_DATE('07-OCT-2021','DD-MON-YYYY')
	--AND   D.DISPATCH_DATE = TO_DATE('19-AUG-2009','DD-MON-YYYY')
	AND   R.STORE_NO = H.TO_WHSE
	AND	  h.TO_WHSE  = i.STORE_NO
	AND   H.FROM_WHSE=I.FROM_WHSE
	AND   H.FROM_WHSE <> '10'
	and	  r.store_no <> '10'
	AND   H.TRANS_TYPE= I.TRANS_TYPE
	AND   R.DEPT_NO IN ('500','6011','502')
	AND   I.WIDTH IN ('00')
	AND	  H.WHO_REQ NOT IN ('AUTORESUPP')
	AND	  H.TRANS_HDR_STATUS NOT IN ('C')
	--and   r.store_no in (':store_code')
	--and length(r.store_no) < 6
	--and		h.trans_no not in (select trans_no from transfer_day)
  -- AND   R.STORE_NO NOT IN ('999004')
	GROUP BY R.STORE_NO, I.ITEM_NO, I.WIDTH, 'RM63', 
NULL, I.TRANS_NO;
	COMMIT;
	
	--INSERT STORE DATA TO STORE_STK_RIMS
	--NON FOOTWEAR
	INSERT INTO STORE_STK_RIMS (RM_NO,TRANS_NO,STORE_NO,ITEM_NO,WIDTH,TSTOCK,S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13)
	SELECT 'RM63',I.TRANS_NO,R.STORE_NO,SUBSTR(I.ITEM_NO,2,8) ITEM,I.WIDTH,SUM(NVL(I.RELEASED_QTY,0)) TOTAL_PAIRS,
	NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
	--FROM WHS_TRANS_HDR H, WHS_TRANS_ITEM I, STORE R, TRANSFER_DAY D
	FROM WHS_TRANS_HDR H, WHS_TRANS_ITEM I, STORE R
	WHERE H.TRANS_NO=I.TRANS_NO
	--AND   D.DISPATCH_DATE BETWEEN :startdate and :enddate
	--and   H.TRANS_NO=D.TRANS_NO
	--AND   D.TRANS_NO=I.TRANS_NO
	--AND   H.SHIP_DATE BETWEEN :startdate and :enddate
    -- AND   H.FROM_DATE =  TO_DATE('24-MAY-2021','DD-MON-YYYY')
      AND  H.FROM_DATE = TRUNC(SYSDATE)-1
      --AND    H.FROM_DATE = TO_DATE('07-OCT-2021', 'DD-MON-YYYY')
	--AND   H.FROM_DATE -- BETWEEN :startdate and :enddate
	--AND   D.DISPATCH_DATE BETWEEN TO_DATE('06-NOV-2009','DD-MON-YYYY') AND TO_DATE('16-NOV-2009','DD-MON-YYYY')
	--AND   D.DISPATCH_DATE = TO_DATE('26-AUG-2009','DD-MON-YYYY')
	AND   R.STORE_NO = H.TO_WHSE
	AND	  h.TO_WHSE  = i.STORE_NO
	AND   H.FROM_WHSE=I.FROM_WHSE
	AND   H.FROM_WHSE <> '10'
	and		r.store_no <> '10'
	AND   H.TRANS_TYPE= I.TRANS_TYPE
	AND   R.DEPT_NO IN ('500','501','502')
	AND   I.WIDTH IN ('CL')
	AND	  H.WHO_REQ NOT IN ('AUTORESUPP')
	AND	  H.TRANS_HDR_STATUS NOT IN ('C')
	--and length(r.store_no) < 6
	--and		h.trans_no not in (select trans_no from transfer_day)
	--and   r.store_no =':store_code'
	--AND   R.STORE_NO NOT IN ('999004')
	GROUP BY R.STORE_NO, I.ITEM_NO, I.WIDTH, 'RM63', 
NULL, I.TRANS_NO;
	COMMIT;

END;